# Generated by Django 4.2.15 on 2025-12-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discord_User",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("username", models.TextField(max_length=32)),
                ("global_name", models.TextField(max_length=32)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_id",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.discord_user",
            ),
        ),
    ]
