# Generated by Django 4.2.15 on 2025-12-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-created_at"]},
        ),
    ]
